mysql_databases:
  - name: "{{ db_name }}"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ db_user }}"
    host: "%"
    password: "{{ db_pass }}"
    priv: "{{ db_name }}.*:ALL"

mysql_root_password: "{{ db_pass }}"
