# The user to run nginx
nginx_user: "www-data"

# A list of hashs that define the servers for nginx,
# as with http parameters. Any valid server parameters
# can be defined here.
nginx_sites:
  default:
    - listen 80
    - server_name _
    - root "/var/www/web"
    - location / { try_files $uri /app.php$is_args$args; }
    - location ~ ^/(app_dev|config)\.php(/|$) {
        fastcgi_pass fpm_socket;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;
      }
    - location ~ ^/app\.php(/|$) {
        fastcgi_pass fpm_socket;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;
        internal;
      }

# A list of hashs that define additional configuration
nginx_configs:
  proxy:
      - proxy_set_header X-Real-IP $remote_addr
      - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
  upstream:
      - upstream fpm_socket { server unix:/var/run/php5-fpm.sock weight=10; }
  gzip:
      - gzip on
      - gzip_vary on
      - gzip_disable msie6
      - gzip_buffers 64 8k
      - gzip_comp_level 9
      - gzip_types text/plain application/atom+xml text/xml application/xml application/javascript application/x-javascript text/javascript text/css text/json application/json