php_enable_php_fpm: true
php_enable_webserver: true
php_webserver_daemon: "nginx"
php_memory_limit: "512M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_date_timezone: "Europe/Riga"
php_packages:
  - php5
  - php5-cli
  - php5-common
  - php5-fpm
  - php5-dev
  - php5-gd
  - php5-intl
  - php5-mcrypt
  - php5-curl
  - php5-mysql
  - php5-redis
  - php5-imagick
  - php-pear
